
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 226839 bytes/channel
 *	Total Size: 1 * 226839 + 4 (header) = 226883 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/gameSong.wav
 *	Time-stamp: Wed Nov 28 04:07:19 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 226839

extern const unsigned char gameSong[226839];

#endif /* __GAMESONGH__ */
