
/**************************************************************
 *	
 *	hitbird, 8 bit, 11025Hz,
 *	1 channel, 6586 bytes/channel
 *	Total Size: 1 * 6586 + 4 (header) = 6630 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/hitbird.wav
 *	Time-stamp: Wed Nov 28 04:07:32 2018
 *	
 **************************************************************/

#ifndef __HITBIRDH__
#define __HITBIRDH__

#define HITBIRDFREQ 11025
#define HITBIRDLEN 6586

extern const unsigned char hitbird[6586];

#endif /* __HITBIRDH__ */
