
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 3308256 bytes/channel
 *	Total Size: 1 * 3308256 + 4 (header) = 3308300 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/loseSong.wav
 *	Time-stamp: Mon Dec 03 12:03:20 2018
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 3308256

extern const unsigned char loseSong[3308256];

#endif /* __LOSESONGH__ */
