
/**************************************************************
 *	
 *	matchSound, 8 bit, 11025Hz,
 *	1 channel, 19369 bytes/channel
 *	Total Size: 1 * 19369 + 4 (header) = 19413 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/matchSound.wav
 *	Time-stamp: Wed Nov 28 17:10:36 2018
 *	
 **************************************************************/

#ifndef __MATCHSOUNDH__
#define __MATCHSOUNDH__

#define MATCHSOUNDFREQ 11025
#define MATCHSOUNDLEN 19369

extern const unsigned char matchSound[19369];

#endif /* __MATCHSOUNDH__ */
