
/**************************************************************
 *	
 *	pauseSong, 8 bit, 11025Hz,
 *	1 channel, 1581696 bytes/channel
 *	Total Size: 1 * 1581696 + 4 (header) = 1581740 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/pauseSong.wav
 *	Time-stamp: Wed Nov 28 16:42:45 2018
 *	
 **************************************************************/

#ifndef __PAUSESONGH__
#define __PAUSESONGH__

#define PAUSESONGFREQ 11025
#define PAUSESONGLEN 1581696

extern const unsigned char pauseSong[1581696];

#endif /* __PAUSESONGH__ */
