
/**************************************************************
 *	
 *	theme, 8 bit, 11025Hz,
 *	1 channel, 1197216 bytes/channel
 *	Total Size: 1 * 1197216 + 4 (header) = 1197260 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/theme.wav
 *	Time-stamp: Wed Nov 28 04:09:24 2018
 *	
 **************************************************************/

#ifndef __THEMEH__
#define __THEMEH__

#define THEMEFREQ 11025
#define THEMELEN 1197216

extern const unsigned char theme[1197216];

#endif /* __THEMEH__ */
