
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 1685664 bytes/channel
 *	Total Size: 1 * 1685664 + 4 (header) = 1685708 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/ziwei/Documents/M3/winSong.wav
 *	Time-stamp: Mon Dec 03 12:03:05 2018
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 1685664

extern const unsigned char winSong[1685664];

#endif /* __WINSONGH__ */
